# Generated by Django 4.2.7 on 2025-03-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="is_confirmed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
